name: Trigger Pages Build

on:
  push:
    branches:
      - main
    paths:
      - '_posts/**'
      - '!python_codes/**'
      - '!scripts/**'
      - '!requirements.txt'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_FOR_DISPATCH }}
          repository: SehwanHong/SehwanHong.github.io
          event-type: ai-repo-updated